[package]
name = "mutato"
version = "1.0.0"
authors = ["Matti Annala <matti.annala@tuni.fi>", "Anssi Nurminen <anssi.nurminen@tuni.fi>"]

[dependencies]
docopt = "*"
bio = "0.31"
rust-htslib = "0.31"
lazy_static = "*"
